export const CURRENCIES = [
    { code: 'USD', name: 'Dólar Americano', flag: '🇺🇸', symbol: 'US$' },
    { code: 'EUR', name: 'Euro', flag: '🇪🇺', symbol: '€' },
    { code: 'BRL', name: 'Real Brasileiro', flag: '🇧🇷', symbol: 'R$' },
    { code: 'GBP', name: 'Libra Esterlina', flag: '🇬🇧', symbol: '£' },
    { code: 'ARS', name: 'Peso Argentino', flag: '🇦🇷', symbol: 'ARS$' },
    { code: 'JPY', name: 'Iene Japonês', flag: '🇯🇵', symbol: '¥' },
    { code: 'CAD', name: 'Dólar Canadense', flag: '🇨🇦', symbol: 'C$' },
    { code: 'AUD', name: 'Dólar Australiano', flag: '🇦🇺', symbol: 'A$' },
    { code: 'CHF', name: 'Franco Suíço', flag: '🇨🇭', symbol: 'Fr' },
    { code: 'CNY', name: 'Yuan Chinês', flag: '🇨🇳', symbol: '¥' },
    { code: 'INR', name: 'Rúpia Indiana', flag: '🇮🇳', symbol: '₹' },
    { code: 'MXN', name: 'Peso Mexicano', flag: '🇲🇽', symbol: '$' },
    { code: 'ZAR', name: 'Rand Sul-Africano', flag: '🇿🇦', symbol: 'R' },
    { code: 'NZD', name: 'Dólar Neozelandês', flag: '🇳🇿', symbol: 'NZ$' },
    { code: 'SGD', name: 'Dólar de Cingapura', flag: '🇸🇬', symbol: 'S$' },
    { code: 'HKD', name: 'Dólar de Hong Kong', flag: '🇭🇰', symbol: 'HK$' },
    { code: 'SEK', name: 'Coroa Sueca', flag: '🇸🇪', symbol: 'kr' },
    { code: 'NOK', name: 'Coroa Norueguesa', flag: '🇳🇴', symbol: 'kr' },
    { code: 'DKK', name: 'Coroa Dinamarquesa', flag: '🇩🇰', symbol: 'kr' },
    { code: 'KRW', name: 'Won Sul-Coreano', flag: '🇰🇷', symbol: '₩' },
    { code: 'TRY', name: 'Lira Turca', flag: '🇹🇷', symbol: '₺' },
    { code: 'RUB', name: 'Rublo Russo', flag: '🇷🇺', symbol: '₽' },
    { code: 'THB', name: 'Baht Tailandês', flag: '🇹🇭', symbol: '฿' },
    { code: 'IDR', name: 'Rupia Indonésia', flag: '🇮🇩', symbol: 'Rp' },
    { code: 'MYR', name: 'Ringgit Malaio', flag: '🇲🇾', symbol: 'RM' },
    { code: 'PHP', name: 'Peso Filipino', flag: '🇵🇭', symbol: '₱' },
    { code: 'TWD', name: 'Novo Dólar Taiwanês', flag: '🇹🇼', symbol: 'NT$' },
    { code: 'CZK', name: 'Coroa Checa', flag: '🇨🇿', symbol: 'Kč' },
    { code: 'PLN', name: 'Zloty Polonês', flag: '🇵🇱', symbol: 'zł' },
    { code: 'HUF', name: 'Forint Húngaro', flag: '🇭🇺', symbol: 'Ft' },
    { code: 'ILS', name: 'Novo Shekel Israelense', flag: '🇮🇱', symbol: '₪' },
    { code: 'CLP', name: 'Peso Chileno', flag: '🇨🇱', symbol: '$' },
    { code: 'COP', name: 'Peso Colombiano', flag: '🇨🇴', symbol: '$' },
    { code: 'PEN', name: 'Sol Peruano', flag: '🇵🇪', symbol: 'S/' },
    { code: 'UYU', name: 'Peso Uruguaio', flag: '🇺🇾', symbol: '$U' },
    { code: 'PYG', name: 'Guarani Paraguaio', flag: '🇵🇾', symbol: '₲' },
    { code: 'BOB', name: 'Boliviano', flag: '🇧🇴', symbol: 'Bs.' },
    { code: 'VEF', name: 'Bolívar Venezuelano', flag: '🇻🇪', symbol: 'Bs' },
    { code: 'AED', name: 'Dirham dos Emirados', flag: '🇦🇪', symbol: 'د.إ' },
    { code: 'SAR', name: 'Riyal Saudita', flag: '🇸🇦', symbol: '﷼' },
    { code: 'QAR', name: 'Rial Catariano', flag: '🇶🇦', symbol: 'ر.ق' },
    { code: 'KWD', name: 'Dinar Kuwaitiano', flag: '🇰🇼', symbol: 'د.ك' },
    { code: 'BHD', name: 'Dinar Bareinita', flag: '🇧🇭', symbol: '.د.ب' },
    { code: 'OMR', name: 'Rial Omanense', flag: '🇴🇲', symbol: 'ر.ع.' },
    { code: 'MAD', name: 'Dirham Marroquino', flag: '🇲🇦', symbol: 'د.م.' },
    { code: 'EGP', name: 'Libra Egípcia', flag: '🇪🇬', symbol: 'E£' },
    { code: 'DZD', name: 'Dinar Argelino', flag: '🇩🇿', symbol: 'د.ج' },
    { code: 'NGN', name: 'Naira Nigeriana', flag: '🇳🇬', symbol: '₦' },
    { code: 'KES', name: 'Xelim Queniano', flag: '🇰🇪', symbol: 'KSh' },
    { code: 'GHS', name: 'Cedi Ganês', flag: '🇬🇭', symbol: 'GH₵' },
    { code: 'UGX', name: 'Xelim Ugandês', flag: '🇺🇬', symbol: 'USh' },
    { code: 'TZS', name: 'Xelim Tanzaniano', flag: '🇹🇿', symbol: 'TSh' },
    { code: 'BTC', name: 'Bitcoin', flag: '₿', symbol: '₿' },
    { code: 'ETH', name: 'Ethereum', flag: '⧫', symbol: 'ETH' },
    { code: 'RON', name: 'Leu Romeno', flag: '🇷🇴', symbol: 'lei' },
    { code: 'BGN', name: 'Lev Búlgaro', flag: '🇧🇬', symbol: 'лв' },
    { code: 'RSD', name: 'Dinar Sérvio', flag: '🇷🇸', symbol: 'дин' },
    { code: 'ISK', name: 'Coroa Islandesa', flag: '🇮🇸', symbol: 'kr' },
    { code: 'HRK', name: 'Kuna Croata', flag: '🇭🇷', symbol: 'kn' },
    { code: 'UAH', name: 'Hryvnia Ucraniano', flag: '🇺🇦', symbol: '₴' },
    { code: 'KZT', name: 'Tenge Cazaque', flag: '🇰🇿', symbol: '₸' },
    { code: 'VND', name: 'Dong Vietnamita', flag: '🇻🇳', symbol: '₫' },
    { code: 'PKR', name: 'Rúpia Paquistanesa', flag: '🇵🇰', symbol: '₨' },
    { code: 'BDT', name: 'Taka de Bangladesh', flag: '🇧🇩', symbol: '৳' },
    { code: 'LKR', name: 'Rúpia Cingalesa', flag: '🇱🇰', symbol: 'Rs' },
    { code: 'MMK', name: 'Kyat de Mianmar', flag: '🇲🇲', symbol: 'K' },
    { code: 'KHR', name: 'Riel Cambojano', flag: '🇰🇭', symbol: '៛' },
    { code: 'LAK', name: 'Kip Laosiano', flag: '🇱🇦', symbol: '₭' },
    { code: 'BND', name: 'Dólar de Brunei', flag: '🇧🇳', symbol: 'B$' },
    { code: 'MOP', name: 'Pataca de Macau', flag: '🇲🇴', symbol: 'MOP$' },
    { code: 'FJD', name: 'Dólar Fijiano', flag: '🇫🇯', symbol: 'FJ$' },
    { code: 'XPF', name: 'Franco CFP', flag: '🇵🇫', symbol: '₣' },
    { code: 'JMD', name: 'Dólar Jamaicano', flag: '🇯🇲', symbol: 'J$' },
    { code: 'TTD', name: 'Dólar de Trinidad e Tobago', flag: '🇹🇹', symbol: 'TT$' },
    { code: 'DOP', name: 'Peso Dominicano', flag: '🇩🇴', symbol: 'RD$' },
    { code: 'CUP', name: 'Peso Cubano', flag: '🇨🇺', symbol: '₱' },
    { code: 'CRC', name: 'Colón Costarriquenho', flag: '🇨🇷', symbol: '₡' },
    { code: 'PAB', name: 'Balboa Panamenho', flag: '🇵🇦', symbol: 'B/.' },
    { code: 'GTQ', name: 'Quetzal Guatemalteco', flag: '🇬🇹', symbol: 'Q' },
    { code: 'HNL', name: 'Lempira Hondurenha', flag: '🇭🇳', symbol: 'L' },
    { code: 'NIO', name: 'Córdoba Nicaraguense', flag: '🇳🇮', symbol: 'C$' },
    { code: 'BZD', name: 'Dólar do Belize', flag: '🇧🇿', symbol: 'BZ$' },
    { code: 'BSD', name: 'Dólar Bahamense', flag: '🇧🇸', symbol: 'B$' },
    { code: 'BBD', name: 'Dólar Barbadense', flag: '🇧🇧', symbol: 'Bds$' },
    { code: 'BAM', name: 'Marco Conversível', flag: '🇧🇦', symbol: 'KM' },
    { code: 'ALL', name: 'Lek Albanês', flag: '🇦🇱', symbol: 'L' },
    { code: 'MKD', name: 'Dinar Macedônio', flag: '🇲🇰', symbol: 'ден' },
    { code: 'MDL', name: 'Leu Moldavo', flag: '🇲🇩', symbol: 'L' },
    { code: 'AMD', name: 'Dram Armênio', flag: '🇦🇲', symbol: '֏' },
    { code: 'AZN', name: 'Manat Azeri', flag: '🇦🇿', symbol: '₼' },
    { code: 'GEL', name: 'Lari Georgiano', flag: '🇬🇪', symbol: '₾' },
    { code: 'UZS', name: 'Som Uzbeque', flag: '🇺🇿', symbol: "so'm" },
    { code: 'XAF', name: 'Franco CFA Central', flag: '🇨🇲', symbol: 'FCFA' },
    { code: 'XOF', name: 'Franco CFA Ocidental', flag: '🇸🇳', symbol: 'CFA' },
    { code: 'MUR', name: 'Rúpia Mauriciana', flag: '🇲🇺', symbol: '₨' },
    { code: 'MGA', name: 'Ariary Malgaxe', flag: '🇲🇬', symbol: 'Ar' },
    { code: 'MZN', name: 'Metical Moçambicano', flag: '🇲🇿', symbol: 'MT' },
    { code: 'AOA', name: 'Kwanza Angolano', flag: '🇦🇴', symbol: 'Kz' },
    { code: 'ZMW', name: 'Kwacha Zambiano', flag: '🇿🇲', symbol: 'ZK' },
    { code: 'BWP', name: 'Pula de Botsuana', flag: '🇧🇼', symbol: 'P' },
]
